### ISSUE TITLE
Wrong temperature shown on 2.1.0

### ISSUE THREAD

**Issue by yeSpud** [DanielStormApps/Fanny#41]
There are 2 different temperatures being shown for the CPU. 

It should be noted before updating to version 2.1.0 smcFanControl and Fanny showed the same temperature for the CPU. After updating Fanny shows different, higher temperatures. 

<img width="180" alt="Screen Shot 2020-03-25 at 10 27 44" src="https://user-images.githubusercontent.com/10385195/77573344-60164780-6e85-11ea-90ef-4243a3f5fe2e.png">

Computer information:
* Model: Late 2015 MacBook Pro (13 inch)
* OS: Mac OS 10.15.3

**Comment by yeSpud** [comment]
I don't think these temperatures are possible (the fan wasn't even ramping up)

<img width="180" alt="hot" src="https://cdn.discordapp.com/attachments/634215238073581579/692271268136878140/Screen_Shot_2020-03-24_at_23.18.33.png">

**Comment by DanielStormApps** [comment]
v2.1.0 now calculates the CPU and GPU temperature as an average from know sensors. This was done to avoid Fanny not working on devices that did not have the certain sensor Fanny was previously using. 
https://github.com/DanielStormApps/SMC/blob/dab934613d562d087231c21afbcbabc14ba0d24e/smc/SMC/Hardware/SMC%2BCPU.swift#L24

With that said though those temperatures do seem high in your second message. I don’t have anything to compare them to so I’m unsure though. It could be an issue with one of the sensors on your machine giving an abnormal reading, that SMC should filter out if that’s the case. 

I’ll spin up a small SMC app that’ll display the temperatures of each sensor it’s reading for you to run on your machine so that I can get a clearer picture. Will attach the SMC app to this thread once it’s ready and let you know.

**Comment by DanielStormApps** [comment]
Please refer to https://github.com/DanielStormApps/Fanny/issues/45#issuecomment-612454274
