### ISSUE TITLE
Temperature inconsistent with terminal output

### ISSUE THREAD

**Issue by AdityaPrakash-26** [DanielStormApps/Fanny#85]
Hello!

First of all, thanks for this application :)

The temperature shown by Fanny is inconsistent to what I am seeing on my terminal using the following command:
`sudo powermetrics --samplers smc |grep -i "CPU die temperature"`

I am attaching the screenshots below:

Fanny output:
<img width="186" alt="Screenshot 2022-08-27 at 12 24 53 AM" src="https://user-images.githubusercontent.com/55011564/186972874-36a85a59-e2cc-4249-838c-552da39e03bb.png">

Terminal Output:
<img width="570" alt="Screenshot 2022-08-27 at 12 24 47 AM" src="https://user-images.githubusercontent.com/55011564/186972927-2102d33e-5c3e-4bfa-ab91-916b5a762dd2.png">

My specs:
Model: 27" late-2015 iMac
OS: macOS 12.15
Processor: 3.3GHz Quad-Core Intel i5
RAM: 8 GB 1867 MHz DDR3
GPU: AMD Radeon R9 M395 2GB

**Comment by daltonbr** [comment]
Hi @AdityaPrakash-26, I am not that familiar with this software - I just installed this app today for testing, but I may have an answer.

In `Preferences`, you can adjust the `CPU Sensor` to `Die` instead of the default value `Average`.
For me, it is consistent with the CLI command you suggested.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/10944679/219371676-ca2d1617-4fbe-41d0-a934-cfaceb606606.png">

**Comment by AdityaPrakash-26** [comment]
Didn't know that. Thanks!
